daily_dashboard/forms/settings.py
from wtforms import RadioField, DecimalField, StringField, HiddenField
from wtforms.validators import Optional, NumberRange, Length, InputRequired

from daily_dashboard.forms.csrf import CSRF_Form
from daily_dashboard.forms.custom_fields import MultiCheckboxField
from daily_dashboard.forms.custom_validators import RequiredIf


class SettingsForm(CSRF_Form):

    device_uuid = HiddenField(
        u'Device UUID',
        validators=[
            InputRequired()
        ],
        description='The device UUID.'
    )

    device_name = StringField(
        u'Device Name',
        description='A friendly name for this device so it can be easily identified.',
        validators=[
            Length(max=20),
            Optional()
        ]
    )

    date_format = RadioField(
        u'Date Format',
        description='Determines how to display the date.',
        choices=[
            ('MDY', 'MDY (i.e. January 1 2020)'),
            ('DMY', 'DMY (i.e. 1 January 2020)'),
            ('YMD', 'YMD (i.e. 2020 January 1)')
        ],
        default='MDY',
    )

    time_format = RadioField(
        u'Time Format',
        description='Determines how to display the time.',
        choices=[
            ('12hr', '5:00 PM'),
            ('24hr', '17:00'),
        ],
        default='12hr',
    )

    calendars = MultiCheckboxField(
        u'Displayed Calendars',
        description='Choose which calendars to display on the dashboard.'
    )

    lat = DecimalField(u'Latitude', places=2, validators=[
        RequiredIf('lon', message='Required if setting Longitude'),
        NumberRange(min=-90.0, max=90.0),
        Optional()
    ])
    lon = DecimalField(u'Longitude', places=2, validators=[
        RequiredIf('lat', message='Required if setting Latitude'),
        NumberRange(min=-180.0, max=180.0),
        Optional()
    ])

daily_dashboard/routes/active_sessions.py
from flask import Blueprint, render_template, g
from flask_login import login_required, current_user

from daily_dashboard.dto.device_dto import DeviceDto
from daily_dashboard.helpers.credential_manager import use_credentials
from daily_dashboard.helpers.device_manager import use_device
from daily_dashboard.providers.google.calendars import get_calendar_list

bp = Blueprint('sessions', __name__, url_prefix='/sessions')


@bp.route('/', methods=('GET',))
@login_required
@use_credentials
@use_device
def active():
    calendar_list = get_calendar_list(g.credentials)
    device_dtos = [
        DeviceDto(device, is_current=(device.id == g.device.id), calendar_list=calendar_list)
        for device in current_user.devices
    ]

    return render_template('active_sessions.html', devices=device_dtos)

daily_dashboard/routes/dashboard.py
from datetime import datetime

from flask import Blueprint, render_template, session, redirect, url_for, request, g, abort
from flask_login import login_required, current_user

from daily_dashboard.data_access.devices import update_device_settings, get_device_by_uuid
from daily_dashboard.forms.settings import SettingsForm
from daily_dashboard.helpers.credential_manager import use_credentials
from daily_dashboard.helpers.device_manager import use_device
from daily_dashboard.providers.google.calendars import get_calendar_list
from daily_dashboard.routes.google import oauth_limited_input_device

bp = Blueprint('main', __name__)


@bp.route('/')
@login_required
@use_device
def dashboard():
    """
    Sends basic dashboard template.

    :return: The template
    """

    # session variable for max_days not implemented yet
    max_days = 7  # session.get('max_days', 7)

    date_order = ('date', 'month') if g.device.date_order == 'DMY' else ('month', 'date')

    return render_template(
        'dashboard.html',
        card_count=max_days,
        date_order=date_order,
        clock_24hr=g.device.time_24hour,
        external_login_endpoint=url_for('main.login', _external=True),
        position_set=g.device.position is not None
    )


@bp.route('/settings', methods=('GET', 'POST'))
@login_required
@use_credentials
@use_device
def settings():
    """
    View and update user settings

    GET -- returns JSON representing user settings
    POST -- updates user settings

    :return:
    """
    form = SettingsForm(request.form)

    calendar_list = get_calendar_list(g.credentials)

    form.calendars.choices = [
        (calendar['id'], calendar['summary'], (calendar['id'] in g.device.watched_calendars))
        for calendar in calendar_list
    ]

    if request.method == 'POST' and form.validate():
        device = g.device

        if 'device_uuid' in request.form:
            uuid = request.args.get('uuid', None)
            device = get_device_by_uuid(uuid)
            if device is None:
                return abort(404)

        update_device_settings(
            device,
            name=form.device_name.data,
            date_order=form.date_format.data,
            time_24hour=form.time_format.data == '24hr',
            calendars=form.calendars.data,
            position=dict(lat=form.lat.data, lon=form.lon.data)
        )

        return redirect(url_for('index'))

    device = g.device
    if 'uuid' in request.args:
        uuid = request.args.get('uuid', None)
        device = get_device_by_uuid(uuid)
        if device is None:
            return abort(404)
        elif device.user_id != current_user.id:
            return abort(403)

    # prefill location info
    if device.position is not None:
        lat, lon = device.position
        if lat:
            form.lat.data = lat
        if lon:
            form.lon.data = lon

    form.device_uuid.data = device.uuid

    if g.device.name:
        form.device_name.data = device.name

    # set the selected date_format value
    form.date_format.data = device.date_order

    # set the selected time_format value
    form.time_format.data = '24hr' if device.time_24hour else '12hr'

    return render_template(
        'settings.html',
        form=form,
        current_device=(g.device.id == device.id)
    )


@bp.route('/login')
def login():
    if 'device_credentials' not in session or datetime.utcnow() > session['device_credentials']['valid_until']:
        session['device_credentials'] = oauth_limited_input_device.create_device_credentials()

    return render_template('login.html', device_credentials=session['device_credentials'])

daily_dashboard/templates/active_sessions.html
{% extends 'layouts/bootstrap.html' %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/navbar.css') }}">
{% endblock %}

{% block content %}

{% include 'layouts/navbar.html' with context %}

<div class="container py-2">
    <h1 class="text-center">{% block title %}Active Sessions{% endblock %}</h1>
    <p></p>

    {% if devices|length == 0 %}
        <p>No current devices authenticated. <a href="{{ url_for('index') }}">Click here to view your dashboard from this device.</a></p>
    {% else %}

        {# display forms for each device #}
        {% for device in devices %}
            <div class="row my-2">
                <div class="card w-100">
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            {% set device_name = device.name or 'Unnamed device' %}
                            <h3 class="card-title">{{ device_name }}
                                {% if device.is_current %}
                                <span class="text-secondary"> (this device)</span>
                                {% endif %}
                            </h3>
                            <a href="{{ url_for('main.settings', uuid=device.uuid) }}">Edit</a>
                        </div>
                        <div class="card-text">
                            <p><span class="h5">Date Format:</span> {{ device.date_order }}</p>
                            <p><span class="h5">Time Format:</span> {{ device.time_format }}</p>
                            <p><span class="h5">Timezone:</span> {{ device.timezone }}</p>
                            <p><span class="h5">Weather Location:</span> {{ device.position }}</p>
                            <h5>Watched Calendars:</h5>
                            {%- set calendars = device.calendar_summaries or device.calendars -%}
                            <ul class="list-group col-lg-6">
                            {%- for calendar in calendars -%}
                                <li class="list-group-item border-0">{{ calendar }}</li>
                            {%- endfor -%}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

    {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">//test script</script>
{% endblock %}

daily_dashboard/templates/base.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <title>{% block title %}{% endblock %} | {{ brand.name }}</title>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/base.css') }}">
        {% block head %}{% endblock %}
    </head>

    <body>
        {# an area to add navigation before the main content on pages that require it #}
        {% block navigation %}{% endblock %}

        <main class="content">
            {% block content %}{% endblock %}
        </main>

        {% block scripts %}{% endblock %}
    </body>
</html>

daily_dashboard/templates/dashboard.html
{% extends 'layouts/base.html' %}

{% block title %}Home{% endblock %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/flash.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/dashboard.css') }}">
{% endblock %}

{% block content %}
    <section id="info">
        <div id="flash--container" class="flash--container top">
            {% for category, message in get_flashed_messages(with_categories=true) %}
            <p class="flash {{ category }}">{{ message }}</p>
            {% endfor %}
        </div>
        <a id="settings" href="{{ url_for('main.settings') }}">
            <img id="qr-settings" src="{{ url_for('static', filename='images/settings.png') }}" alt="Settings" />
        </a>
        <h1 id="clock"></h1>
    </section>
    <section id="primary">
        {% include 'components/date_card.html' %}
    </section>

    <section id="secondary">
        {% for n in range(card_count - 1) %}
            {% include 'components/date_card.html' %}
        {% endfor %}
    </section>
{% endblock %}

{% block scripts %}
    <script type="module" src="{{ url_for('static', filename='scripts/general.mjs') }}"></script>

    <script type="text/javascript">
        const TIME_OPTIONS = {
            hour: 'numeric',
            minute: '2-digit',
            hour12: !{{ clock_24hr|lower }},
        };
    </script>
    <script type="module" src="{{ url_for('static', filename='scripts/dashboard/clock.mjs') }}"></script>

    <script type="text/javascript">
        const CALENDAR_ENDPOINT = "{{ url_for('calendar_api.events') }}";
    </script>
    <script type="module" src="{{ url_for('static', filename='scripts/dashboard/calendarEvents.mjs') }}"></script>

    <script type="text/javascript" src="{{ url_for('static', filename='scripts/dashboard/skycons.js') }}"></script>
    <script type="text/javascript">
        const WEATHER_ENDPOINT = "{{ url_for('weather_api.forecast') }}";
    </script>
    <script type="module" src="{{ url_for('static', filename='scripts/dashboard/weather.mjs') }}"></script>

    <script type="text/javascript">
        const LOGIN_EXTERNAL_ENDPOINT = "{{ external_login_endpoint }}";
        const DEVICE_ENDPOINT = "{{ url_for('device_api.current_device') }}";
        const locationSet = {{ position_set|tojson }};
    </script>
    <script type="module" src="{{ url_for('static', filename='scripts/location.mjs') }}"></script>
    <script type="module" src="{{ url_for('static', filename='scripts/dashboard/index.mjs') }}"></script>
{% endblock %}

daily_dashboard/templates/error.html
{% extends 'layouts/base.html' %}

{% block title %}Error{% endblock %}

{% block content %}
    <h1>{{ error.status }} | {{ error.title }}</h1>
    <p>{{ error.message }}</p>
{% endblock %}

daily_dashboard/templates/login.html
{% extends 'layouts/base.html' %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/navbar.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/login.css') }}">
{% endblock %}

{% block title %}Login{% endblock %}

{% block navigation %}
    {% include 'layouts/navbar.html' with context %}
{% endblock %}

{% block content %}
    <div id="flash--container">
        {% for category, message in get_flashed_messages(with_categories=true) %}
        <p class="flash {{ category }}">{{ message }}</p>
        {% endfor %}
    </div>

    <h1 class="page--header">Authentication</h1>
    <p>Visit <a href="{{ device_credentials.verification_url }}">{{ device_credentials.verification_url }}</a>
        from another device and enter the code below.</p>
    <div class="action--items">
<!--        <span class="encircle">Visit</span>-->
        <img id="google-qr-url" src="{{ url_for('static', filename='images/google-device-authentication.png') }}" />
<!--        <span class="encircle">then enter</span>-->
        <p id="device--code">{{ device_credentials.user_code }}</p>
    </div>

    <p class="whisper">Want to login directly from this device? <a href="{{ url_for('oauth.authorize') }}">Click here</a></p>
{% endblock %}


{% block scripts %}
    <script>
        const pollUrl = "{{ url_for('oauth_lid.poll') }}";
    </script>
    <script src="{{ url_for('static', filename='scripts/login.js') }}"></script>
{% endblock %}

daily_dashboard/templates/settings.html
{% extends 'layouts/bootstrap.html' %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/navbar.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/flash.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/settings.css') }}">
{% endblock %}

{% block title %}Settings{% endblock %}

{% block content %}
    {% include 'layouts/navbar.html' with context %}

    <div class="container-fluid row p-4">

        {# Navigation #}
        <div id="sidebar" class="col col-md-3 col-lg-2" style="height:auto;">
            <div class="d-flex flex-md-column justify-content-between">
                <ul class="nav flex-column">
                    <li class="nav-item"><a href="#general" class="nav-link h4">General</a></li>
                    <li class="nav-item"><a href="#calendar" class="nav-link h4">Calendar</a></li>
                    <li class="nav--item"><a href="#weather" class="nav-link h4">Weather</a></li>
                    <li class="nav--item"><a href="#active-sessions" class="nav-link h4">Active Sessions</a></li>
                    <li class="nav-item"><a href="#authentication" class="nav-link h4">Authentication</a></li>
                </ul>
            </div>
            <button id="settings-submit" class="btn btn-lg font-weight-bold w-100 my-2">Save</button>
        </div>

        <div class="col-md-9 col-lg-10">
            <div id="flash--container" class="bottom">
                {%- for category, message in get_flashed_messages(with_categories=true) -%}
                <p class="flash {{ category }}">{{ message }}</p>
                {%- endfor -%}
            </div>

            <form id="settings--form" method="post">
                {{ form.csrf_token }}
                {{ form.device_uuid() }}
                <div id="general" class="mx-1 my-2 py-2 px-3 border border-secondary">
                    <h2 class="my-2">General</h2>

                    <div class="form-group my-3">
                        {{ form.device_name.label(class='h5') }}
                        {{ form.device_name(class='ml-2 p-1') }}
                    </div>

                    <div class="form-group my-2">
                        {{ form.date_format.label(class='h5') }}
                        <p>{{ form.date_format.description }}</p>
                        {{ form.date_format(class='form--list') }}
                    </div>

                    <div class="form-group my-2">
                        {{ form.time_format.label(class='h5') }}
                        <p>{{ form.time_format.description }}</p>
                        {{ form.time_format(class='form--list mb-0') }}
                    </div>
                </div>

                <div id="calendar" class="mx-1 my-2 py-2 px-3 border border-secondary">
                    <h2 class="my-2">Calendar</h2>

                    <div class="form-group my-2">
                        {{ form.calendars.label(class='h5') }}
                        <p>{{ form.calendars.description }}</p>
                        {{ form.calendars(class='form--list') }}
                    </div>
                </div>

                <div id="weather" class="mx-1 my-2 py-2 px-3 border border-secondary">
                    <h2 class="my-2">Weather</h2>
                    <h5>Location</h5>
                    <p>Set a location for local weather.</p>

                    <button id="btn-uselocation" class="btn btn-sm rounded mb-2" type="button">Use Your Location</button>

                    <div class="form-group my-2 row">
                        <div class="col-md-6 col-xl-4 my-2">
                            {{ form.lat.label(class='h5') }}
                            {{ form.lat(id='location-lat', class='p-1') }}
                            {% for error in form.lat.errors %}
                            <p class="text-danger py-1">*{{ error }}</p>
                            {% endfor %}
                        </div>

                        <div class="col-md-6 col-xl-4 my-2">
                            {{ form.lon.label(class='h5') }}
                            {{ form.lon(id='location-lon', class='p-1') }}
                            {% for error in form.lon.errors %}
                            <p class="text-danger py-1">*{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </form>

            <div id="active-sessions" class="mx-1 my-2 py-3 px-3 border border-secondary">
                <h2 class="my-2">Active Sessions</h2>
                <a href="{{ url_for('sessions.active') }}" class="btn">View All Active Device Sessions</a>
            </div>

            <div id="authentication" class="mx-1 my-2 py-2 px-3 border border-secondary">
                <h2 class="my-2">Authentication</h2>
                <div class="row">
                    {%- if current_device -%}
                    <div class="form-group col-md col-lg-4 mb-0">
                        <a id="btn-logout" href="{{ url_for('oauth.logout') }}" class="btn btn-danger my-2" role="button">Logout</a>
                        <p>Logout of this device.</p>
                    </div>
                    {% endif %}

                    <div class="form-group col-md col-lg-4 mb-0">
                        <a id="btn-deauthorize" href="{{ url_for('oauth.revoke') }}" class="btn btn-danger my-2" role="button">Deauthorize</a>
                        <p>Revoke access to this application. Doing this will cause other devices you are logged into to stop working.</p>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        {# add event listener to submit button on sidebar #}
        const saveButton = document.getElementById("settings-submit");
        const settingsForm = document.getElementById("settings--form");
        saveButton.addEventListener("click", () => settingsForm.submit());
    </script>

    <script type="module">
        import { requestLocation } from "{{ url_for('static', filename='scripts/location.mjs') }}";

        function setFromGeolocation() {
            const latTextbox = document.getElementById("location-lat");
            const lonTextbox = document.getElementById("location-lon");

            requestLocation()
                .then(geolocation => {
                    const { latitude, longitude } = geolocation.coords;

                    if (latitude && longitude) {
                        latTextbox.value = latitude;
                        lonTextbox.value = longitude;
                    } else {
                        throw Error("Latitude and/or longitude could not be obtained from navigator.geolocation");
                    }
                }).catch(err => {
                    console.error(err);
                    alert("Could not get location. Share your location or update it manually.");
                });
        }

        const useLocationButton = document.getElementById("btn-uselocation");
        useLocationButton.addEventListener("click", setFromGeolocation);
    </script>
{% endblock %}